services:
  backend:
    container_name: back-costcontrol-nodejs
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./Backend:/app
    depends_on:
      - mysql_db
    networks:
      - costcontrol_network

  frontend:
    container_name: front-costcontrol-reactjs
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - costcontrol_network

  mysql_db:
    container_name: database-costcontrol-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin123*
      MYSQL_DATABASE: costcontrol
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin123*
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - costcontrol_network
    
volumes:
  db-data: {}

networks:
  costcontrol_network:
    driver: bridge

  #Comandos en cmd
  #docker compose up --build si pongo -d no veo la consola docker compose up -d --build